### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by cxstles** [Ccode-lang/cvm#1]
If you're gonna try to make a language in python at least create the following:
* Compiler
* Lexer
* Tokenizer
* Parser

**Comment by Ccode-lang** [comment]
1. This was never meant to be a useful language.
2. This was a learning experiment I did to fill time and have fun, not to make a working language.
3. This is no longer in development and I have no plans for it.

**Comment by cxstles** [comment]
> 1. This was never meant to be a useful language.
> 2. This was a learning experiment I did to fill time and have fun, not to make a working language.
> 3. This is no longer in development and I have no plans for it.

I don't even remember making this issue at all. 💀
